services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app:rw
    # env_file:
    #     - ./.env
    environment:
      - ENV=docker
    command: poetry run uvicorn --reload app.api.main:app --host 0.0.0.0 --port 8000
    # depends_on:
    #   - postgres

#   postgres:
#     image: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# volumes:
#   postgres-db: