"""Add description to activities

Revision ID: 4c49e526fe7d
Revises: 082c76ef0431
Create Date: 2024-09-29 15:03:12.035013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c49e526fe7d'
down_revision: Union[str, None] = '082c76ef0431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'description')
    # ### end Alembic commands ###
