"""Initial migration from existing database

Revision ID: 634f1ab07e10
Revises: 
Create Date: 2024-10-04 20:14:20.440401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '634f1ab07e10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
        sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['partner_id'], ['users.id'], name='users_partner_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='users_pkey')
    )

    # Then, create the activities table
    op.create_table('activities',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('activity_name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('budget', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('link_info', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='activities_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='activities_pkey')
    )

    op.create_index('ix_app_schema_users_id', 'users', ['id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint from activities to users
    op.drop_constraint('activities_user_id_fkey', table_name='activities')

    # Then drop the tables
    op.drop_table('users')
    op.drop_table('activities')
    # ### end Alembic commands ###
