name: Unit Tests in CI for Fast API application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run unit tests and save coverage output
        run: poetry run pytest --cov=app tests/ | tee pytest-coverage.txt

      - name: Commit coverage report
        uses: EndBug/add-and-commit@v9  # Or another action that commits
        with:
          add: 'pytest-coverage.txt'
          author_name: 'Riboulet Ronan'
          author_email: 'ronanriboulet@gmail.com'
          message: 'Update pytest-coverage.txt [skip ci]' 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}